# Modules
modules:
  backgrounds: true
  bossbars: true
  images: true

resource-pack:
  # extract the minecraft bars.png
  extract-bar-image: true
  # Your namespace
  namespace: "justbossbar"
  # Font Name
  font: "default"
  # Customize the folder where png files should be generated.
  # This is useful for those who want to keep their resource pack structure in order.
  image-path:
    backgrounds: 'font\backgrounds\'
    images: 'font\images\'
    space-split: 'font\base\'
  # The initial character of a font
  # 字体的初始字符
  initial-char: '뀁'
  # Unicode Support for 1.20+ clients
  # This would make your resource pack about 900KB bigger
  support-1_20-unicodes: false

other-settings:
  # default width
  # 默认文字宽度
  default-character-width: 8
