name: JustBossbar
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.17
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - ItemsAdder

libraries:
  - dev.dejvokep:boosted-yaml:1.3

commands:
  justbossbar:
    usage: /justbossbar

permissions:
  justbossbar.*:
    description: Gives access to all nameplates commands
    children:
      justbossbar.reload: true
      justbossbar.help: true

  justbossbar.reload:
    default: op
  justbossbar.help:
    default: op