name: JustBossbar
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.17
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - ItemsAdder

libraries:
  - dev.dejvokep:boosted-yaml:1.3

commands:
  customnameplates:
    usage: /customnameplates
    aliases:
      - nameplates

permissions:
  nameplates.*:
    description: Gives access to all nameplates commands
    children:
      nameplates.reload: true
      nameplates.help: true

  nameplates.reload:
    default: op
  nameplates.help:
    default: op