name: JustBossbar
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.17
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
  - PlaceholderAPI
softdepend:
  - ItemsAdder
commands:
  customnameplates:
    usage: /customnameplates
    aliases:
      - nameplates

permissions:
  nameplates.*:
    description: Gives access to all nameplates commands
    children:
      nameplates.reload: true
      nameplates.forceequip: true
      nameplates.forceunequip: true
      nameplates.help: true
      nameplates.unequip: true
      nameplates.preview: true
      nameplates.list: true
      nameplates.about: true

  nameplates.reload:
    default: op
  nameplates.forceequip:
    default: op
  nameplates.forceunequip:
    default: op
  nameplates.help:
    default: op
  nameplates.about:
    default: op
  nameplates.unequip:
    default: true
  nameplates.preview:
    default: true
  nameplates.list:
    default: true
  nameplates.equip:
    default: true