# %nameplates_background_{0}%
background-text:
  player:
    background: bedrock_1
    text: '%nameplates_unicode_hello%'
    remove-shadow: true

# %nameplates_descent_{0}%
# If the character can't show correctly here, use descent-unicode instead
descent-text:
  player:
    text: "%player_name%"
    descent: 5

# %nameplates_unicode_{0}%
descent-unicode:
  hello:
    text: "Hello 여보세요 你好 こんにちは"
    descent: 5
